name: Run All Tests

on:
  pull_request:
    types: [
      opened,
      labeled,
      ready_for_review,
      reopened,
      synchronize,
    ]
    branches:
      - main
      - release**
      - production**
      - hotfix**
      - lab**

env:
  NODE_VERSION: '14.x'

jobs:
  type:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: yarn install
    - run: yarn test
