name: Run All Tests

on:
  pull_request:
    types: [
      opened,
      labeled,
      ready_for_review,
      reopened,
      synchronize,
    ]
    branches:
      - main
      - release**
      - production**
      - hotfix**
      - lab**

env:
  NODE_VERSION: '14.x'

jobs:
  Type:
    if: |
      github.event.pull_request.draft == false ||
      (
        github.event.action == 'labeled' &&
        contains(github.event.pull_request.labels.*.name, 'run-all-test')
      )
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - run: yarn install
    - run: yarn test:type

  Unit-Test:
    if: |
      github.event.pull_request.draft == false ||
      (
        github.event.action == 'labeled' &&
        contains(github.event.pull_request.labels.*.name, 'run-all-test')
      )
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install
    - run: yarn test:unit
